# NBA Player Statistics
Edwin Dely

June 5, 2018

## Background

The topic of my project is the statistics of every NBA player in the 2017-2018 season. I hope to know understand what attributes that the player brings to their specific teams. The source of the datasheet comes from MySportsFeeds. The information in the datasheet includes the weight, height, name, age, games played, and shot attempts/makes.

## Data

Intersted in a relationship between variables which are age and 2 pt field goals made.

In [67]:
import pandas as pd
import numpy as np
df=pd.read_csv("nba_player_stats_2017_18.csv")
df.loc[:,["Age","Fg2PtMade"]]

df_sub = df[df["Age"] > 0]
df_sub.head()

,Player_ID,LastName,FirstName,Jersey_Num,Position,Height,Weight,Birth_Date,Age,Birth_City,...,Team_Abbr.,Team_City,Team_Name,GamesPlayed,Fg2PtAtt,Fg2PtMade,Fg3PtAtt,Fg3PtMade,FtAtt,FtMade
0,10138,Abrines,Alex,8.0,SG,"6'6""",190.0,8/1/93,24,Palma de Mallorca,...,OKL,Oklahoma City,Thunder,75,70,31,221,84,46,39
1,9466,Acy,Quincy,13.0,PF,"6'7""",240.0,10/6/90,27,"Tyler, TX",...,BRO,Brooklyn,Nets,70,73,28,292,102,60,49
2,9390,Adams,Steven,12.0,C,"7'0""",255.0,7/20/93,24,Rotorua,...,OKL,Oklahoma City,Thunder,76,710,448,2,0,287,160
3,13742,Adebayo,Bam,13.0,C,"6'10""",255.0,7/18/97,20,"Newark, NJ",...,MIA,Miami,Heat,69,333,174,7,0,179,129
4,9375,Afflalo,Arron,4.0,SG,"6'5""",210.0,10/15/85,32,"Los Angeles, CA",...,ORL,Orlando,Magic,52,92,38,70,27,26,22
5,9357,Ajinca,Alexis,42.0,C,"7'2""",248.0,5/6/88,30,Saint-Etienne,...,NOP,New Orleans,Pelicans,0,0,0,0,0,0,0
6,9272,Aldrich,Cole,45.0,C,"6'11""",253.0,10/31/88,29,"Burnsville, MN",...,MIN,Minnesota,Timberwolves,21,15,5,0,0,6,2
7,9480,Aldridge,LaMarcus,12.0,PF,"6'11""",260.0,7/19/85,32,"Dallas, TX",...,SAS,San Antonio,Spurs,75,1255,660,92,27,399,334
8,13749,Allen,Jarrett,31.0,C,"6'11""",234.0,4/21/98,20,"Austin, TX",...,BRO,Brooklyn,Nets,72,382,229,15,5,147,114
9,13776,Allen,Kadeem,45.0,SG,"6'3""",200.0,1/15/93,25,"Wilmington, NC",...,BOS,Boston,Celtics,18,11,6,11,0,9,7
10,9299,Allen,Tony,24.0,SF,"6'4""",213.0,1/10/82,36,"Chicago, IL",...,CHI,Chicago,Bulls,22,79,40,12,4,21,11
11,9452,Aminu,Al-Farouq,8.0,PF,"6'9""",220.0,9/21/90,27,"Atlanta, GA",...,POR,Portland,Trail Blazers,69,243,105,339,125,80,59
12,9527,Anderson,Alan,26.0,SG,"6'6""",220.0,10/16/82,35,"Minneapolis, MN",...,LAC,Los Angeles,Clippers,0,0,0,0,0,0,0
13,9178,Anderson,Justin,1.0,SF,"6'6""",230.0,11/19/93,24,"Montross, VA",...,PHI,Philadelphia,76ers,38,99,53,103,34,38,28
14,9475,Anderson,Kyle,1.0,SF,"6'9""",230.0,9/20/93,24,"New York, NY",...,SAS,San Antonio,Spurs,74,381,212,57,19,146,104
15,9353,Anderson,Ryan,33.0,PF,"6'10""",240.0,5/6/88,30,"Sacramento, CA",...,HOU,Houston,Rockets,66,141,76,339,131,93,72
16,13796,Anigbogu,Ike,13.0,C,"6'10""",262.0,10/16/98,19,"San Diego, CA",...,IND,Indiana,Pacers,11,9,4,0,0,6,5
17,9325,Antetokounmpo,Giannis,34.0,SF,"6'11""",222.0,12/6/94,23,Athens,...,MIL,Milwaukee,Bucks,75,1262,699,140,43,641,487
18,9369,Anthony,Carmelo,7.0,PF,"6'8""",240.0,5/29/84,34,"New York, NY",...,OKL,Oklahoma City,Thunder,78,695,303,474,169,193,148
19,13750,Anunoby,OG,3.0,SF,"6'8""",235.0,7/17/97,20,London,...,TOR,Toronto,Raptors,74,149,90,197,73,62,39
20,11884,Arcidiacono,Ryan,10.0,G,"6'3""",195.0,3/26/94,24,"Langhorne, PA",...,CHI,Chicago,Bulls,24,10,8,31,9,6,5
21,9235,Ariza,Trevor,1.0,SF,"6'8""",215.0,6/30/85,32,"Miami, FL",...,HOU,Houston,Rockets,67,189,98,462,170,89,76
22,9198,Arthur,Darrell,0.0,PF,"6'9""",235.0,3/25/88,30,"Dallas, TX",...,DEN,Denver,Nuggets,19,24,14,23,8,3,2
23,13805,Artis,Jamiel,NaN,SG,"6'7""",213.0,1/12/93,25,"Baltimore, MD",...,ORL,Orlando,Magic,15,50,23,29,8,12,7
24,9358,Asik,Omer,3.0,C,"7'0""",255.0,7/3/86,31,Bursa,...,CHI,Chicago,Bulls,18,22,9,0,0,13,4
26,9190,Augustin,D.J.,14.0,PG,"6'0""",183.0,11/10/87,30,"New Orleans, LA",...,ORL,Orlando,Magic,75,267,130,272,114,189,164
27,9360,Babbitt,Luke,8.0,PF,"6'9""",225.0,6/19/89,28,"Cincinnati, OH",...,MIA,Miami,Heat,50,59,31,156,60,22,17
28,13788,Bacon,Dwayne,7.0,SF,"6'7""",221.0,8/30/95,22,"Lakeland, FL",...,CHA,Charlotte,Hornets,53,150,61,43,11,25,20
29,10102,Baker,Ron,31.0,PG,"6'4""",220.0,3/30/93,25,"Hays, KS",...,NYK,New York,Knicks,29,26,9,33,11,27,20
30,10131,Baldwin IV,Wade,4.0,G,"6'4""",202.0,3/26/96,22,"Belle Mead, NJ",...,POR,Portland,Trail Blazers,7,16,10,5,4,10,6

In [32]:
Age=df['Age']
print('Age stats')
a=np.min(Age)
print('min=',a)
b=np.max(Age)
print('max=',b)
c=np.mean(Age)
print('mean=', c)
d=np.std(Age)
print('standard deviation=', d)

print('Fg2PtMade stats')
fg=df['Fg2PtMade']
a=np.min(fg)
print('min=',a)
b=np.max(fg)
print('max=',b)
c=np.mean(fg)
print('mean=', c)
d=np.std(fg)
print('standard deviation=', d)

Age stats
min= 0
max= 41
mean= 24.65909090909091
standard deviation= 7.854026295072076
Fg2PtMade stats
min= 0
max= 725
mean= 116.27759740259741
standard deviation= 135.5555400313413

In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt

age = df_sub["Age"]
age.head()

fig1 = plt.figure()
plt.hist(age)
plt.title("Age")
plt.show()
fig1.savefig('Age.png')

fg = df_sub["Fg2PtMade"]
fg.head()

fig2 = plt.figure()
plt.hist(fg)
plt.title("Fg2PtMade")
plt.show()
fig2.savefig('fg.png')

fig3 = plt.figure()
plt.scatter(age, fg)
plt.title("Scatter")
plt.xlabel("Age")
plt.ylabel("Fg2PtMade")
plt.show()
fig3.savefig('Scat.png')

NameError: name 'df_sub' is not defined

## Analysis

## Conclusion